Show additional information on JSON decoding issue in Java client library (#152)
* passing meaningful information into an exception when deserialization goes wrong.
The current message looke like this:

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected STRING but was BEGIN_OBJECT at path $.records[0]

We need to get more info to figure out what's the actual issue.

* Add missing import and comments in java template

---------

Co-authored-by: Davide Vacca <134616519+dvacca-onfido@users.noreply.github.com>